[tool.black]
line-length = 140


[tool.pytest.ini_options]
pythonpath = "src"
python_files = "Test*.py"
python_classes = "Test*"
python_functions = "test*"


[tool.coverage.html]
directory = "coverage/htmlcov"

[tool.coverage.run]
branch = true
data_file = "coverage/.coverage"

[tool.mypy]
files = ["src/**/*.py"]
mypy_path = "src"
explicit_package_bases = true
disable_error_code = ["import-untyped"] # WIP: Try to get everything typed
