taxNumber: davcna
taxpayerType: FO
name: ime priimek
address1: naslov
address2: 
city: mesto
postNumber: postna
postName: posta
municipalityName: obcina
birthDate: 2024-01-01
maticnaStevilka: maticna
invalidskoPodjetje: false
resident: true
activityCode: 
activityName: 
countryID: 
countryName: 