name: Run Tests (node, lib)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vitest:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Install lcov
        run: sudo apt-get install -y -qq --no-install-recommends lcov

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: lib/package.json

      - name: Install dependencies
        run: pnpm install
        working-directory: lib

      - name: Run tests with coverage
        run: pnpm test:coverage
        working-directory: lib

      - name: Report coverage
        id: coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: lib/coverage/lcov.info
          working-directory: lib
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: vitest-code-coverage-report
          update-comment: true

      - name: Update coverage badge JSON
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mkdir -p .github/badges
          echo "{\"coverage\": \"${{ steps.coverage.outputs.total-coverage }}%\"}" > .github/badges/vitest-coverage.json

      - name: Commit coverage badge JSON
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: update vitest coverage badge"
          file_pattern: .github/badges/vitest-coverage.json
          branch: badges/vitest
          create_branch: true
          push_options: "--force"
